spring:
  profiles:
    active: local, sensitive
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 1000
        use_sql_comments: true # QueryDsl 실행 쿼리를 jpql로도 보고 싶을 때

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

